/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.commonalities.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tools.vitruv.dsls.commonalities.CommonalitiesLanguageRuntimeModule;
import tools.vitruv.dsls.commonalities.CommonalitiesLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CommonalitiesLanguageIdeSetup extends CommonalitiesLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    CommonalitiesLanguageRuntimeModule _commonalitiesLanguageRuntimeModule = new CommonalitiesLanguageRuntimeModule();
    CommonalitiesLanguageIdeModule _commonalitiesLanguageIdeModule = new CommonalitiesLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_commonalitiesLanguageRuntimeModule, _commonalitiesLanguageIdeModule));
  }
}
