version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "Maven"
    include: "scope"
  groups:
    junit:
      patterns:
      - "org.junit.*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "GitHub Actions"
    include: "scope"
- package-ecosystem: npm
  directory: "/reactions/vscode-plugin"
  schedule:
    interval: daily
  commit-message:
    prefix: "NPM"
    include: "scope"