package tools.vitruv.dsls.demo.insurancepersons.persons2insurance

class PersonsToInsuranceChangePropagationSpecification extends mir.reactions.personsToInsurance.PersonsToInsuranceChangePropagationSpecification {
}
