/*
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import tools.vitruv.dsls.reactions.ui.internal.ReactionsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReactionsLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ReactionsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ReactionsActivator activator = ReactionsActivator.getInstance();
		return activator != null ? activator.getInjector(ReactionsActivator.TOOLS_VITRUV_DSLS_REACTIONS_REACTIONSLANGUAGE) : null;
	}

}
