/*
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractCommonalitiesLanguageScopeProvider extends XbaseBatchScopeProvider {
}
