/*
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ReactionsLanguageEditor extends XbaseEditor {
}
