/*
 * generated by Xtext 2.37.0
 */
package tools.vitruv.dsls.reactions.ide
import tools.vitruv.dsls.reactions.ide.AbstractReactionsLanguageIdeModule

/**
 * Use this class to register ide components.
 */
class ReactionsLanguageIdeModule extends AbstractReactionsLanguageIdeModule {
}
