/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.commonalities.ui.labeling;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class CommonalitiesLanguageDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
  @Override
  public Object text(final IEObjectDescription description) {
    return this.text(description.getEObjectOrProxy(), description);
  }

  public Object text(final EObject object, final IEObjectDescription description) {
    return super.text(description);
  }

  /**
   * def dispatch text(Metaclass metaclass, IEObjectDescription description) {
   * new StyledString()
   * .append(description.name.firstSegment, QUALIFIER_STYLER)
   * .append(DOMAIN_METACLASS_SEPARATOR, QUALIFIER_STYLER)
   * .append(description.name.getSegment(1))
   * }
   */
  @Override
  public Object image(final IEObjectDescription ele) {
    String _name = ele.getEClass().getName();
    return (_name + ".gif");
  }
}
