/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.ConcreteModelChange;
import tools.vitruv.dsls.reactions.language.LanguagePackage;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.TriggerImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Concrete Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConcreteModelChangeImpl extends TriggerImpl implements ConcreteModelChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConcreteModelChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.CONCRETE_MODEL_CHANGE;
  }

} //ConcreteModelChangeImpl
