/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.ElementRemovalAsRootChangeType;
import tools.vitruv.dsls.reactions.language.LanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element Removal As Root Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ElementRemovalAsRootChangeTypeImpl extends ElementRootChangeTypeImpl implements ElementRemovalAsRootChangeType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementRemovalAsRootChangeTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.ELEMENT_REMOVAL_AS_ROOT_CHANGE_TYPE;
  }

} //ElementRemovalAsRootChangeTypeImpl
