/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.LanguagePackage;
import tools.vitruv.dsls.reactions.language.ModelAttributeRemovedChange;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model Attribute Removed Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ModelAttributeRemovedChangeImpl extends ModelAttributeChangeImpl implements ModelAttributeRemovedChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelAttributeRemovedChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.MODEL_ATTRIBUTE_REMOVED_CHANGE;
  }

} //ModelAttributeRemovedChangeImpl
