/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.LanguagePackage;
import tools.vitruv.dsls.reactions.language.RequireAbscenceOfModelElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Require Abscence Of Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RequireAbscenceOfModelElementImpl extends RetrieveOrRequireAbscenceOfModelElementImpl implements RequireAbscenceOfModelElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequireAbscenceOfModelElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.REQUIRE_ABSCENCE_OF_MODEL_ELEMENT;
  }

} //RequireAbscenceOfModelElementImpl
