/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import tools.vitruv.dsls.commonalities.language.Commonality;
import tools.vitruv.dsls.commonalities.language.CommonalityReference;
import tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping;
import tools.vitruv.dsls.commonalities.language.LanguagePackage;

import tools.vitruv.dsls.commonalities.language.elements.ClassLike;
import tools.vitruv.dsls.commonalities.language.elements.Classifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Commonality Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.impl.CommonalityReferenceImpl#getClassLikeContainer <em>Class Like Container</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.impl.CommonalityReferenceImpl#isMultiValued <em>Multi Valued</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.impl.CommonalityReferenceImpl#getName <em>Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.impl.CommonalityReferenceImpl#getReferenceType <em>Reference Type</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.impl.CommonalityReferenceImpl#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CommonalityReferenceImpl extends MinimalEObjectImpl.Container implements CommonalityReference
{
  /**
   * The default value of the '{@link #isMultiValued() <em>Multi Valued</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMultiValued()
   * @generated
   * @ordered
   */
  protected static final boolean MULTI_VALUED_EDEFAULT = false;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getReferenceType() <em>Reference Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferenceType()
   * @generated
   * @ordered
   */
  protected Commonality referenceType;

  /**
   * The cached value of the '{@link #getMappings() <em>Mappings</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMappings()
   * @generated
   * @ordered
   */
  protected EList<CommonalityReferenceMapping> mappings;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CommonalityReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.COMMONALITY_REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassLike getClassLikeContainer()
  {
    ClassLike classLikeContainer = basicGetClassLikeContainer();
    return classLikeContainer != null && classLikeContainer.eIsProxy() ? (ClassLike)eResolveProxy((InternalEObject)classLikeContainer) : classLikeContainer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassLike basicGetClassLikeContainer()
  {
    // TODO: implement this method to return the 'Class Like Container' reference
    // -> do not perform proxy resolution
    // Ensure that you remove @generated or mark it @generated NOT
    throw new UnsupportedOperationException();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isMultiValued()
  {
    // TODO: implement this method to return the 'Multi Valued' attribute
    // Ensure that you remove @generated or mark it @generated NOT
    throw new UnsupportedOperationException();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.COMMONALITY_REFERENCE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Commonality getReferenceType()
  {
    if (referenceType != null && referenceType.eIsProxy())
    {
      InternalEObject oldReferenceType = (InternalEObject)referenceType;
      referenceType = (Commonality)eResolveProxy(oldReferenceType);
      if (referenceType != oldReferenceType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, LanguagePackage.COMMONALITY_REFERENCE__REFERENCE_TYPE, oldReferenceType, referenceType));
      }
    }
    return referenceType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Commonality basicGetReferenceType()
  {
    return referenceType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReferenceType(Commonality newReferenceType)
  {
    Commonality oldReferenceType = referenceType;
    referenceType = newReferenceType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.COMMONALITY_REFERENCE__REFERENCE_TYPE, oldReferenceType, referenceType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CommonalityReferenceMapping> getMappings()
  {
    if (mappings == null)
    {
      mappings = new EObjectContainmentEList<CommonalityReferenceMapping>(CommonalityReferenceMapping.class, this, LanguagePackage.COMMONALITY_REFERENCE__MAPPINGS);
    }
    return mappings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Classifier getType()
  {
    // TODO: implement this method
    // Ensure that you remove @generated or mark it @generated NOT
    throw new UnsupportedOperationException();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LanguagePackage.COMMONALITY_REFERENCE__MAPPINGS:
        return ((InternalEList<?>)getMappings()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LanguagePackage.COMMONALITY_REFERENCE__CLASS_LIKE_CONTAINER:
        if (resolve) return getClassLikeContainer();
        return basicGetClassLikeContainer();
      case LanguagePackage.COMMONALITY_REFERENCE__MULTI_VALUED:
        return isMultiValued();
      case LanguagePackage.COMMONALITY_REFERENCE__NAME:
        return getName();
      case LanguagePackage.COMMONALITY_REFERENCE__REFERENCE_TYPE:
        if (resolve) return getReferenceType();
        return basicGetReferenceType();
      case LanguagePackage.COMMONALITY_REFERENCE__MAPPINGS:
        return getMappings();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LanguagePackage.COMMONALITY_REFERENCE__NAME:
        setName((String)newValue);
        return;
      case LanguagePackage.COMMONALITY_REFERENCE__REFERENCE_TYPE:
        setReferenceType((Commonality)newValue);
        return;
      case LanguagePackage.COMMONALITY_REFERENCE__MAPPINGS:
        getMappings().clear();
        getMappings().addAll((Collection<? extends CommonalityReferenceMapping>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LanguagePackage.COMMONALITY_REFERENCE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LanguagePackage.COMMONALITY_REFERENCE__REFERENCE_TYPE:
        setReferenceType((Commonality)null);
        return;
      case LanguagePackage.COMMONALITY_REFERENCE__MAPPINGS:
        getMappings().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LanguagePackage.COMMONALITY_REFERENCE__CLASS_LIKE_CONTAINER:
        return basicGetClassLikeContainer() != null;
      case LanguagePackage.COMMONALITY_REFERENCE__MULTI_VALUED:
        return isMultiValued() != MULTI_VALUED_EDEFAULT;
      case LanguagePackage.COMMONALITY_REFERENCE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LanguagePackage.COMMONALITY_REFERENCE__REFERENCE_TYPE:
        return referenceType != null;
      case LanguagePackage.COMMONALITY_REFERENCE__MAPPINGS:
        return mappings != null && !mappings.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //CommonalityReferenceImpl
