/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.commonalities.language.EnforcedParticipationCondition;
import tools.vitruv.dsls.commonalities.language.LanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enforced Participation Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EnforcedParticipationConditionImpl extends ParticipationConditionImpl implements EnforcedParticipationCondition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnforcedParticipationConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.ENFORCED_PARTICIPATION_CONDITION;
  }

} //EnforcedParticipationConditionImpl
