/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tools.vitruv.dsls.commonalities.language.LanguagePackage;
import tools.vitruv.dsls.commonalities.language.ParticipationPart;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Participation Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ParticipationPartImpl extends MinimalEObjectImpl.Container implements ParticipationPart
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParticipationPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.PARTICIPATION_PART;
  }

} //ParticipationPartImpl
