package tools.vitruv.dsls.demo.insurancefamilies.insurance2families

class InsuranceToFamiliesChangePropagationSpecification extends mir.reactions.insuranceToFamilies.InsuranceToFamiliesChangePropagationSpecification {
	
}