/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.service.SingletonBinding;
import tools.vitruv.dsls.reactions.ui.validation.ReactionsLanguageEclipseValidator;
import tools.vitruv.dsls.reactions.validation.ReactionsLanguageValidator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReactionsLanguageUiModule extends AbstractReactionsLanguageUiModule {
  @SingletonBinding(eager = true)
  public Class<? extends ReactionsLanguageValidator> bindReactionsLanguageValidator() {
    return ReactionsLanguageEclipseValidator.class;
  }

  public ReactionsLanguageUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
