package tools.vitruv.dsls.demo.insurancefamilies.families2insurance;

class FamiliesToInsuranceChangePropagationSpecification extends mir.reactions.familiesToInsurance.FamiliesToInsuranceChangePropagationSpecification {
	
}
