<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pfandmodel" nsURI="http://www.example.org/pfandmodel" nsPrefix="pfandmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Flasche"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dose"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kasten">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enthält" lowerBound="16"
        upperBound="16" eType="#//Flasche"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pfandelement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPfandelement1" eType="#//Dose"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPfandelement2" eType="#//Kasten"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPfandelement3" eType="#//Flasche"/>
  </eClassifiers>
</ecore:EPackage>
