/*
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CommonalitiesLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tools/vitruv/dsls/commonalities/parser/antlr/internal/InternalCommonalitiesLanguage.tokens");
	}
}
