/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.commonalities.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.service.SingletonBinding;
import tools.vitruv.dsls.commonalities.ui.validation.CommonalitiesLanguageEclipseValidator;
import tools.vitruv.dsls.commonalities.validation.CommonalitiesLanguageValidator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CommonalitiesLanguageUiModule extends AbstractCommonalitiesLanguageUiModule {
  @SingletonBinding(eager = true)
  public Class<? extends CommonalitiesLanguageValidator> bindCommonalitiesLanguageValidator() {
    return CommonalitiesLanguageEclipseValidator.class;
  }

  public CommonalitiesLanguageUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
