package tools.vitruv.dsls.commonalities.tests.execution;

import java.nio.file.Path;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Pair;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import tools.vitruv.testutils.TestProject;

/**
 * Inherits the Identified execution tests, but uses modified commonalities that use aliases
 */
@DisplayName("executing commonalities with aliases")
@SuppressWarnings("all")
public class AliasesExecutionTest extends IdentifiedExecutionTest {
  @BeforeAll
  @Override
  public void generate(@TestProject final Path testProject) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import \"http://tools.vitruv.testutils.metamodels.allElementTypes\" as AllElementTypes");
    _builder.newLine();
    _builder.append("import \"http://tools.vitruv.testutils.metamodels.allElementTypes2\" as AllElementTypes2");
    _builder.newLine();
    _builder.append("import \"http://tools.vitruv.testutils.metamodels.pcm_mockup\" as PcmMockup");
    _builder.newLine();
    _builder.append("import \"http://tools.vitruv.testutils.metamodels.uml_mockup\" as UmlMockup");
    _builder.newLine();
    _builder.newLine();
    _builder.append("concept test");
    _builder.newLine();
    _builder.newLine();
    _builder.append("commonality IdentifiedWithAliases {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("with (AllElementTypes as All):(Root in Resource)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("with AllElementTypes2:(Root2 in Resource)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("with (PcmMockup as Palladio):((Repository as Repo) in (Resource as Res))");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("with UmlMockup:((UPackage as Package) in Resource)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("has id {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= All:Root.id");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= AllElementTypes2:Root2.id2");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= Palladio:Repo.name");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= UmlMockup:Package.name");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("-> All:Resource.name");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("-> AllElementTypes2:Resource.name");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("-> Palladio:Res.name");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("-> UmlMockup:Resource.name");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("has number {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= All:Root.singleValuedEAttribute");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= AllElementTypes2:Root2.singleValuedEAttribute2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("has numberList {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= All:Root.multiValuedEAttribute");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= AllElementTypes2:Root2.multiValuedEAttribute2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("has sub referencing test:SubWithAliases {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= All:Root.multiValuedContainmentEReference");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= AllElementTypes2:Root2.multiValuedContainmentEReference2");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= Palladio:Repo.components");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("= UmlMockup:Package.classes");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    Pair<String, CharSequence> _mappedTo = Pair.<String, CharSequence>of("IdentifiedWithAliases.commonality", _builder.toString());
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("import \"http://tools.vitruv.testutils.metamodels.allElementTypes\" as AllElementTypes");
    _builder_1.newLine();
    _builder_1.append("import \"http://tools.vitruv.testutils.metamodels.allElementTypes2\" as AllElementTypes2");
    _builder_1.newLine();
    _builder_1.append("import \"http://tools.vitruv.testutils.metamodels.pcm_mockup\" as PcmMockup");
    _builder_1.newLine();
    _builder_1.append("import \"http://tools.vitruv.testutils.metamodels.uml_mockup\" as UmlMockup");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("concept test");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("commonality SubWithAliases {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("with AllElementTypes:NonRoot");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("with AllElementTypes2:(NonRoot2 as SecondNonRoot)");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("with (PcmMockup as Palladio):Component");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("with UmlMockup:UClass");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("has name {");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("= AllElementTypes:NonRoot.id");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("= AllElementTypes2:SecondNonRoot.id2");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("= Palladio:Component.name");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("= UmlMockup:UClass.name");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    Pair<String, CharSequence> _mappedTo_1 = Pair.<String, CharSequence>of("SubWithAliases.commonality", _builder_1.toString());
    this.getGenerator().generate(testProject, _mappedTo, _mappedTo_1);
  }
}
