package tools.vitruv.dsls.demo.familiespersons.families2persons

class FamiliesToPersonsChangePropagationSpecification extends mir.reactions.familiesToPersons.FamiliesToPersonsChangePropagationSpecification {

}