/**
 * generated by Xtext 2.9.0
 */
package tools.vitruv.dsls.reactions;

import com.google.inject.Injector;
import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReactionsLanguageStandaloneSetup extends ReactionsLanguageStandaloneSetupGenerated {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    EcorePlugin.ExtensionProcessor.process(null);
    return super.createInjectorAndDoEMFRegistration();
  }

  public static void doSetup() {
    new ReactionsLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
