<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="toplevelelements" nsURI="http://vitruv.tools/dsls/reactions/language/toplevelelements"
    nsPrefix="toplevelelements">
  <eClassifiers xsi:type="ecore:EClass" name="ReactionsFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaceImports" eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xtype#//XImportSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodelImports" upperBound="-1"
        eType="ecore:EClass http://vitruv.tools/dsls/common/elements#//MetamodelImport"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactionsSegments" upperBound="-1"
        eType="#//ReactionsSegment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReactionsSegment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromMetamodels" upperBound="-1"
        eType="ecore:EClass http://vitruv.tools/dsls/common/elements#//MetamodelImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toMetamodels" upperBound="-1"
        eType="ecore:EClass http://vitruv.tools/dsls/common/elements#//MetamodelImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactionsImports" upperBound="-1"
        eType="#//ReactionsImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactions" upperBound="-1"
        eType="#//Reaction" containment="true" eOpposite="#//Reaction/reactionsSegment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routines" upperBound="-1"
        eType="#//Routine" containment="true" eOpposite="#//Routine/reactionsSegment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReactionsImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routinesOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedReactionsSegment"
        eType="#//ReactionsSegment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useQualifiedNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overriddenReactionsSegment"
        eType="#//ReactionsSegment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Trigger"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callRoutine" eType="#//RoutineCall"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactionsSegment" lowerBound="1"
        eType="#//ReactionsSegment" eOpposite="#//ReactionsSegment/reactions"/>
	<eStructuralFeatures xsi:type="ecore:EReference" name="logBlock" eType="#//LogBlock" containment="true" lowerBound="0" upperBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Routine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overrideImportPath" eType="#//RoutineOverrideImportPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//RoutineInput"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchBlock" eType="#//MatchBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createBlock" eType="#//CreateBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactionsSegment" lowerBound="1"
        eType="#//ReactionsSegment" eOpposite="#//ReactionsSegment/routines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateBlock" eType="#//UpdateBlock"
        containment="true"/>
	<eStructuralFeatures xsi:type="ecore:EReference" name="logBlockBeforeMatch" eType="#//LogBlock" containment="true" lowerBound="0" upperBound="1"/>
	<eStructuralFeatures xsi:type="ecore:EReference" name="logBlockBeforeCreate" eType="#//LogBlock" containment="true" lowerBound="0" upperBound="1"/>
	<eStructuralFeatures xsi:type="ecore:EReference" name="logBlockBeforeUpdate" eType="#//LogBlock" containment="true" lowerBound="0" upperBound="1"/>
	<eStructuralFeatures xsi:type="ecore:EReference" name="logBlockAfterUpdate" eType="#//LogBlock" containment="true" lowerBound="0" upperBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutineOverrideImportPath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactionsSegment" eType="#//ReactionsSegment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//RoutineOverrideImportPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutineInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelInputElements" upperBound="-1"
        eType="ecore:EClass http://vitruv.tools/dsls/common/elements#//NamedMetaclassReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaInputElements" upperBound="-1"
        eType="#//NamedJavaElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchStatements" upperBound="-1"
        eType="#//MatchStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createStatements" upperBound="-1"
        eType="ecore:EClass http://vitruv.tools/dsls/common/elements#//NamedMetaclassReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedJavaElementReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/xtext/common/JavaVMTypes#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutineCall" eSuperTypes="#//CodeExecutionBlock"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateBlock" eSuperTypes="#//CodeExecutionBlock"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeExecutionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="code" eType="ecore:EClass http://www.eclipse.org/xtext/xbase/Xbase#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//LogLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//LogDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>     
  </eClassifiers>
   <eClassifiers xsi:type="ecore:EEnum" name="LogLevel">
    <eLiterals name="INFO"/>
    <eLiterals name="DEBUG" value="1"/>
    <eLiterals name="WARN" value="2"/>
    <eLiterals name="ERROR" value="3"/>
  </eClassifiers>
</ecore:EPackage>
