/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Mapping Operand</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getAttributeMappingOperand()
 * @model
 * @generated
 */
public interface AttributeMappingOperand extends Operand
{
} // AttributeMappingOperand
