/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.common.util.EList;

import tools.vitruv.dsls.commonalities.language.elements.Attribute;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commonality Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityReference#getName <em>Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityReference#getReferenceType <em>Reference Type</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityReference#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReference()
 * @model
 * @generated
 */
public interface CommonalityReference extends Attribute
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReference_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityReference#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reference Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Type</em>' reference.
   * @see #setReferenceType(Commonality)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReference_ReferenceType()
   * @model
   * @generated
   */
  Commonality getReferenceType();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityReference#getReferenceType <em>Reference Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Type</em>' reference.
   * @see #getReferenceType()
   * @generated
   */
  void setReferenceType(Commonality value);

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReference_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<CommonalityReferenceMapping> getMappings();

} // CommonalityReference
