/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.common.util.EList;

import tools.vitruv.dsls.commonalities.language.elements.Attribute;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commonality Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityAttribute#getName <em>Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityAttribute#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityAttribute()
 * @model
 * @generated
 */
public interface CommonalityAttribute extends Attribute
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityAttribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.commonalities.language.CommonalityAttributeMapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityAttribute_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<CommonalityAttributeMapping> getMappings();

} // CommonalityAttribute
