/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import tools.vitruv.dsls.common.elements.MetamodelImport;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commonality File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityFile#getOperatorImports <em>Operator Imports</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityFile#getMetamodelImports <em>Metamodel Imports</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityFile#getConcept <em>Concept</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityFile#getCommonality <em>Commonality</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityFile()
 * @model
 * @generated
 */
public interface CommonalityFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Operator Imports</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.commonalities.language.OperatorImport}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator Imports</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityFile_OperatorImports()
   * @model containment="true"
   * @generated
   */
  EList<OperatorImport> getOperatorImports();

  /**
   * Returns the value of the '<em><b>Metamodel Imports</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.common.elements.MetamodelImport}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metamodel Imports</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityFile_MetamodelImports()
   * @model containment="true"
   * @generated
   */
  EList<MetamodelImport> getMetamodelImports();

  /**
   * Returns the value of the '<em><b>Concept</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concept</em>' containment reference.
   * @see #setConcept(Concept)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityFile_Concept()
   * @model containment="true"
   * @generated
   */
  Concept getConcept();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityFile#getConcept <em>Concept</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concept</em>' containment reference.
   * @see #getConcept()
   * @generated
   */
  void setConcept(Concept value);

  /**
   * Returns the value of the '<em><b>Commonality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commonality</em>' containment reference.
   * @see #setCommonality(Commonality)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityFile_Commonality()
   * @model containment="true"
   * @generated
   */
  Commonality getCommonality();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityFile#getCommonality <em>Commonality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commonality</em>' containment reference.
   * @see #getCommonality()
   * @generated
   */
  void setCommonality(Commonality value);

} // CommonalityFile
