/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commonality Attribute Operand</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityAttributeOperand#getAttributeReference <em>Attribute Reference</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityAttributeOperand()
 * @model
 * @generated
 */
public interface CommonalityAttributeOperand extends AttributeMappingOperand
{
  /**
   * Returns the value of the '<em><b>Attribute Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Reference</em>' containment reference.
   * @see #setAttributeReference(CommonalityAttributeReference)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityAttributeOperand_AttributeReference()
   * @model containment="true"
   * @generated
   */
  CommonalityAttributeReference getAttributeReference();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityAttributeOperand#getAttributeReference <em>Attribute Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Reference</em>' containment reference.
   * @see #getAttributeReference()
   * @generated
   */
  void setAttributeReference(CommonalityAttributeReference value);

} // CommonalityAttributeOperand
