/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commonality Reference Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping#isReadAndWrite <em>Read And Write</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping#isWrite <em>Write</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping#isRead <em>Read</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReferenceMapping()
 * @model
 * @generated
 */
public interface CommonalityReferenceMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Read And Write</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read And Write</em>' attribute.
   * @see #setReadAndWrite(boolean)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReferenceMapping_ReadAndWrite()
   * @model
   * @generated
   */
  boolean isReadAndWrite();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping#isReadAndWrite <em>Read And Write</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read And Write</em>' attribute.
   * @see #isReadAndWrite()
   * @generated
   */
  void setReadAndWrite(boolean value);

  /**
   * Returns the value of the '<em><b>Write</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write</em>' attribute.
   * @see #setWrite(boolean)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReferenceMapping_Write()
   * @model
   * @generated
   */
  boolean isWrite();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping#isWrite <em>Write</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write</em>' attribute.
   * @see #isWrite()
   * @generated
   */
  void setWrite(boolean value);

  /**
   * Returns the value of the '<em><b>Read</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read</em>' attribute.
   * @see #setRead(boolean)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getCommonalityReferenceMapping_Read()
   * @model
   * @generated
   */
  boolean isRead();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.CommonalityReferenceMapping#isRead <em>Read</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read</em>' attribute.
   * @see #isRead()
   * @generated
   */
  void setRead(boolean value);

} // CommonalityReferenceMapping
