/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enforced Participation Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getEnforcedParticipationCondition()
 * @model
 * @generated
 */
public interface EnforcedParticipationCondition extends ParticipationCondition
{
} // EnforcedParticipationCondition
