/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage
 * @generated
 */
public interface LanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LanguageFactory eINSTANCE = tools.vitruv.dsls.commonalities.language.impl.LanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Commonality File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality File</em>'.
   * @generated
   */
  CommonalityFile createCommonalityFile();

  /**
   * Returns a new object of class '<em>Operator Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operator Import</em>'.
   * @generated
   */
  OperatorImport createOperatorImport();

  /**
   * Returns a new object of class '<em>Concept</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Concept</em>'.
   * @generated
   */
  Concept createConcept();

  /**
   * Returns a new object of class '<em>Commonality</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality</em>'.
   * @generated
   */
  Commonality createCommonality();

  /**
   * Returns a new object of class '<em>Participation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation</em>'.
   * @generated
   */
  Participation createParticipation();

  /**
   * Returns a new object of class '<em>Participation Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Class</em>'.
   * @generated
   */
  ParticipationClass createParticipationClass();

  /**
   * Returns a new object of class '<em>Participation Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Part</em>'.
   * @generated
   */
  ParticipationPart createParticipationPart();

  /**
   * Returns a new object of class '<em>Participation Relation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Relation</em>'.
   * @generated
   */
  ParticipationRelation createParticipationRelation();

  /**
   * Returns a new object of class '<em>Participation Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Condition</em>'.
   * @generated
   */
  ParticipationCondition createParticipationCondition();

  /**
   * Returns a new object of class '<em>Participation Condition Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Condition Operand</em>'.
   * @generated
   */
  ParticipationConditionOperand createParticipationConditionOperand();

  /**
   * Returns a new object of class '<em>Commonality Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality Attribute</em>'.
   * @generated
   */
  CommonalityAttribute createCommonalityAttribute();

  /**
   * Returns a new object of class '<em>Commonality Attribute Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality Attribute Mapping</em>'.
   * @generated
   */
  CommonalityAttributeMapping createCommonalityAttributeMapping();

  /**
   * Returns a new object of class '<em>Simple Attribute Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Attribute Mapping</em>'.
   * @generated
   */
  SimpleAttributeMapping createSimpleAttributeMapping();

  /**
   * Returns a new object of class '<em>Operator Attribute Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operator Attribute Mapping</em>'.
   * @generated
   */
  OperatorAttributeMapping createOperatorAttributeMapping();

  /**
   * Returns a new object of class '<em>Attribute Mapping Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Mapping Operand</em>'.
   * @generated
   */
  AttributeMappingOperand createAttributeMappingOperand();

  /**
   * Returns a new object of class '<em>Participation Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Attribute</em>'.
   * @generated
   */
  ParticipationAttribute createParticipationAttribute();

  /**
   * Returns a new object of class '<em>Commonality Attribute Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality Attribute Reference</em>'.
   * @generated
   */
  CommonalityAttributeReference createCommonalityAttributeReference();

  /**
   * Returns a new object of class '<em>Commonality Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality Reference</em>'.
   * @generated
   */
  CommonalityReference createCommonalityReference();

  /**
   * Returns a new object of class '<em>Commonality Reference Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality Reference Mapping</em>'.
   * @generated
   */
  CommonalityReferenceMapping createCommonalityReferenceMapping();

  /**
   * Returns a new object of class '<em>Simple Reference Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Reference Mapping</em>'.
   * @generated
   */
  SimpleReferenceMapping createSimpleReferenceMapping();

  /**
   * Returns a new object of class '<em>Operator Reference Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operator Reference Mapping</em>'.
   * @generated
   */
  OperatorReferenceMapping createOperatorReferenceMapping();

  /**
   * Returns a new object of class '<em>Reference Mapping Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference Mapping Operand</em>'.
   * @generated
   */
  ReferenceMappingOperand createReferenceMappingOperand();

  /**
   * Returns a new object of class '<em>Referenced Participation Attribute Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Referenced Participation Attribute Operand</em>'.
   * @generated
   */
  ReferencedParticipationAttributeOperand createReferencedParticipationAttributeOperand();

  /**
   * Returns a new object of class '<em>Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operand</em>'.
   * @generated
   */
  Operand createOperand();

  /**
   * Returns a new object of class '<em>Literal Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Literal Operand</em>'.
   * @generated
   */
  LiteralOperand createLiteralOperand();

  /**
   * Returns a new object of class '<em>Participation Class Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Class Operand</em>'.
   * @generated
   */
  ParticipationClassOperand createParticipationClassOperand();

  /**
   * Returns a new object of class '<em>Participation Attribute Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participation Attribute Operand</em>'.
   * @generated
   */
  ParticipationAttributeOperand createParticipationAttributeOperand();

  /**
   * Returns a new object of class '<em>Commonality Attribute Operand</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commonality Attribute Operand</em>'.
   * @generated
   */
  CommonalityAttributeOperand createCommonalityAttributeOperand();

  /**
   * Returns a new object of class '<em>Bidirectional Participation Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bidirectional Participation Condition</em>'.
   * @generated
   */
  BidirectionalParticipationCondition createBidirectionalParticipationCondition();

  /**
   * Returns a new object of class '<em>Enforced Participation Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enforced Participation Condition</em>'.
   * @generated
   */
  EnforcedParticipationCondition createEnforcedParticipationCondition();

  /**
   * Returns a new object of class '<em>Checked Participation Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Checked Participation Condition</em>'.
   * @generated
   */
  CheckedParticipationCondition createCheckedParticipationCondition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LanguagePackage getLanguagePackage();

} //LanguageFactory
