/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmDeclaredType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator Reference Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.OperatorReferenceMapping#getParticipationClass <em>Participation Class</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.OperatorReferenceMapping#getOperator <em>Operator</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.OperatorReferenceMapping#getOperands <em>Operands</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getOperatorReferenceMapping()
 * @model
 * @generated
 */
public interface OperatorReferenceMapping extends CommonalityReferenceMapping
{
  /**
   * Returns the value of the '<em><b>Participation Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participation Class</em>' reference.
   * @see #setParticipationClass(ParticipationClass)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getOperatorReferenceMapping_ParticipationClass()
   * @model
   * @generated
   */
  ParticipationClass getParticipationClass();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.OperatorReferenceMapping#getParticipationClass <em>Participation Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participation Class</em>' reference.
   * @see #getParticipationClass()
   * @generated
   */
  void setParticipationClass(ParticipationClass value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' reference.
   * @see #setOperator(JvmDeclaredType)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getOperatorReferenceMapping_Operator()
   * @model
   * @generated
   */
  JvmDeclaredType getOperator();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.OperatorReferenceMapping#getOperator <em>Operator</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(JvmDeclaredType value);

  /**
   * Returns the value of the '<em><b>Operands</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.commonalities.language.ReferenceMappingOperand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operands</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getOperatorReferenceMapping_Operands()
   * @model containment="true"
   * @generated
   */
  EList<ReferenceMappingOperand> getOperands();

} // OperatorReferenceMapping
