/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Participation Attribute Operand</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.ParticipationAttributeOperand#getParticipationAttribute <em>Participation Attribute</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipationAttributeOperand()
 * @model
 * @generated
 */
public interface ParticipationAttributeOperand extends ParticipationConditionOperand, AttributeMappingOperand, ReferenceMappingOperand
{
  /**
   * Returns the value of the '<em><b>Participation Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participation Attribute</em>' containment reference.
   * @see #setParticipationAttribute(ParticipationAttribute)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipationAttributeOperand_ParticipationAttribute()
   * @model containment="true"
   * @generated
   */
  ParticipationAttribute getParticipationAttribute();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.ParticipationAttributeOperand#getParticipationAttribute <em>Participation Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participation Attribute</em>' containment reference.
   * @see #getParticipationAttribute()
   * @generated
   */
  void setParticipationAttribute(ParticipationAttribute value);

} // ParticipationAttributeOperand
