/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;

import org.eclipse.emf.common.util.EList;

import tools.vitruv.dsls.commonalities.language.elements.PackageLike;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Participation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.Participation#getDomainName <em>Domain Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.Participation#getDomainAlias <em>Domain Alias</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.Participation#getParts <em>Parts</em>}</li>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.Participation#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipation()
 * @model
 * @generated
 */
public interface Participation extends PackageLike
{
  /**
   * Returns the value of the '<em><b>Domain Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Name</em>' attribute.
   * @see #setDomainName(String)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipation_DomainName()
   * @model
   * @generated
   */
  String getDomainName();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.Participation#getDomainName <em>Domain Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain Name</em>' attribute.
   * @see #getDomainName()
   * @generated
   */
  void setDomainName(String value);

  /**
   * Returns the value of the '<em><b>Domain Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Alias</em>' attribute.
   * @see #setDomainAlias(String)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipation_DomainAlias()
   * @model
   * @generated
   */
  String getDomainAlias();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.Participation#getDomainAlias <em>Domain Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain Alias</em>' attribute.
   * @see #getDomainAlias()
   * @generated
   */
  void setDomainAlias(String value);

  /**
   * Returns the value of the '<em><b>Parts</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.commonalities.language.ParticipationPart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipation_Parts()
   * @model containment="true"
   * @generated
   */
  EList<ParticipationPart> getParts();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.commonalities.language.ParticipationCondition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getParticipation_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<ParticipationCondition> getConditions();

} // Participation
