/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.commonalities.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Attribute Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.commonalities.language.SimpleAttributeMapping#getAttribute <em>Attribute</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getSimpleAttributeMapping()
 * @model
 * @generated
 */
public interface SimpleAttributeMapping extends CommonalityAttributeMapping
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference.
   * @see #setAttribute(ParticipationAttribute)
   * @see tools.vitruv.dsls.commonalities.language.LanguagePackage#getSimpleAttributeMapping_Attribute()
   * @model containment="true"
   * @generated
   */
  ParticipationAttribute getAttribute();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.commonalities.language.SimpleAttributeMapping#getAttribute <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' containment reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(ParticipationAttribute value);

} // SimpleAttributeMapping
