/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.Trigger;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getConcreteModelChange()
 * @model
 * @generated
 */
public interface ConcreteModelChange extends Trigger
{
} // ConcreteModelChange
