/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Deletion Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionChangeType()
 * @model
 * @generated
 */
public interface ElementDeletionChangeType extends ElementExistenceChangeType
{
} // ElementDeletionChangeType
