/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Insertion As Root Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementInsertionAsRootChangeType()
 * @model
 * @generated
 */
public interface ElementInsertionAsRootChangeType extends ElementRootChangeType, ElementInsertionChangeType
{
} // ElementInsertionAsRootChangeType
