/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Replacement Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementReplacementChangeType()
 * @model
 * @generated
 */
public interface ElementReplacementChangeType extends ModelElementUsageChangeType, ElementReferenceChangeType
{
} // ElementReplacementChangeType
