/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;

import org.eclipse.emf.ecore.EObject;

import tools.vitruv.dsls.common.elements.MetaclassEReferenceReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Reference Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ElementReferenceChangeType#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementReferenceChangeType()
 * @model
 * @generated
 */
public interface ElementReferenceChangeType extends EObject
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference.
   * @see #setFeature(MetaclassEReferenceReference)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementReferenceChangeType_Feature()
   * @model containment="true"
   * @generated
   */
  MetaclassEReferenceReference getFeature();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ElementReferenceChangeType#getFeature <em>Feature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' containment reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(MetaclassEReferenceReference value);

} // ElementReferenceChangeType
