/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Attribute Replaced Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getModelAttributeReplacedChange()
 * @model
 * @generated
 */
public interface ModelAttributeReplacedChange extends ModelAttributeChange
{
} // ModelAttributeReplacedChange
