/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Attribute Removed Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getModelAttributeRemovedChange()
 * @model
 * @generated
 */
public interface ModelAttributeRemovedChange extends ModelAttributeChange
{
} // ModelAttributeRemovedChange
