/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.common.elements.MetaclassEAttributeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Attribute Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ModelAttributeChange#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getModelAttributeChange()
 * @model
 * @generated
 */
public interface ModelAttributeChange extends ConcreteModelChange
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference.
   * @see #setFeature(MetaclassEAttributeReference)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getModelAttributeChange_Feature()
   * @model containment="true"
   * @generated
   */
  MetaclassEAttributeReference getFeature();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ModelAttributeChange#getFeature <em>Feature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' containment reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(MetaclassEAttributeReference value);

} // ModelAttributeChange
