/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Require Abscence Of Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRequireAbscenceOfModelElement()
 * @model
 * @generated
 */
public interface RequireAbscenceOfModelElement extends RetrieveOrRequireAbscenceOfModelElement
{
} // RequireAbscenceOfModelElement
