/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Model Element Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveModelElementType()
 * @model
 * @generated
 */
public interface RetrieveModelElementType extends EObject
{
} // RetrieveModelElementType
