/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.RetrieveModelElement#getName <em>Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.RetrieveModelElement#getRetrievalType <em>Retrieval Type</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveModelElement()
 * @model
 * @generated
 */
public interface RetrieveModelElement extends RetrieveOrRequireAbscenceOfModelElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveModelElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.RetrieveModelElement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Retrieval Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retrieval Type</em>' containment reference.
   * @see #setRetrievalType(RetrieveModelElementType)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveModelElement_RetrievalType()
   * @model containment="true"
   * @generated
   */
  RetrieveModelElementType getRetrievalType();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.RetrieveModelElement#getRetrievalType <em>Retrieval Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retrieval Type</em>' containment reference.
   * @see #getRetrievalType()
   * @generated
   */
  void setRetrievalType(RetrieveModelElementType value);

} // RetrieveModelElement
