/**
 * generated by Xtext 2.30.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Many Model Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveManyModelElements()
 * @model
 * @generated
 */
public interface RetrieveManyModelElements extends RetrieveModelElementType
{
} // RetrieveManyModelElements
